# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
# Module is defined directly in the file now
module GogoVersioning
  # Version-specific configurations or methods can be added here
end
"
class GogoAT01 < Formula
  desc "CLI tool for generating Go projects with best practices (v0.1 series)"
  homepage "https://github.com/oculus-core/gogo"
  version "0.1.7"
  license "MIT"

  on_macos do
    on_intel do
      url "https://github.com/oculus-core/gogo/releases/download/v0.1.7/gogo_0.1.7_Darwin_x86_64.tar.gz"
      sha256 "37f215fd7094c856acc3a09506524f64c43c91a2312182c4367659f3b49026d0"

      def install
        bin.install "gogo"
      end
    end
    on_arm do
      url "https://github.com/oculus-core/gogo/releases/download/v0.1.7/gogo_0.1.7_Darwin_arm64.tar.gz"
      sha256 "bcab3415b1b6a2186ed016f9cf30bac22bd8d8ad07b22bdd745b7956013780c9"

      def install
        bin.install "gogo"
      end
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/oculus-core/gogo/releases/download/v0.1.7/gogo_0.1.7_Linux_x86_64.tar.gz"
        sha256 "3cab0227cd98b10a37c792101fce653b72d8a62ad0587a002f29234b515d8e32"

        def install
          bin.install "gogo"
        end
      end
    end
    on_arm do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/oculus-core/gogo/releases/download/v0.1.7/gogo_0.1.7_Linux_arm64.tar.gz"
        sha256 "3b021c9406f12bd9b1cc61f3d571c55f3f2e6186680bfa38273602d3ba59f855"

        def install
          bin.install "gogo"
        end
      end
    end
  end

  include GogoVersioning
  depends_on :macos => :catalina

  test do
    system "#{bin}/gogo", "version"
  end
end
