# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Gogo < Formula
  desc "CLI tool for generating Go projects with best practices"
  homepage "https://github.com/oculus-core/gogo"
  version "0.1.2"
  license "MIT"

  on_macos do
    on_intel do
      url "https://github.com/oculus-core/gogo/releases/download/v0.1.2/gogo_0.1.2_Darwin_x86_64.tar.gz"
      sha256 "bb36dfb211df72457f4a0f8e90bf1b4a9a45a0310b8aaccc81e30ff5682b8945"

      def install
        bin.install "gogo"
      end
    end
    on_arm do
      url "https://github.com/oculus-core/gogo/releases/download/v0.1.2/gogo_0.1.2_Darwin_arm64.tar.gz"
      sha256 "1840a5e00104b5525f3e0d27cd81ca092f3f57779a723bce7723b3e2fd1fa8a9"

      def install
        bin.install "gogo"
      end
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/oculus-core/gogo/releases/download/v0.1.2/gogo_0.1.2_Linux_x86_64.tar.gz"
        sha256 "98ceb5ba7a6ddac785a68bb2edcff27af7f53265c1a18dc784ccf8e8e616ce96"

        def install
          bin.install "gogo"
        end
      end
    end
    on_arm do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/oculus-core/gogo/releases/download/v0.1.2/gogo_0.1.2_Linux_arm64.tar.gz"
        sha256 "12d83c21f8d72e25d024458c61ea44c7ee29b1ca79c82d2be1f7671dab141661"

        def install
          bin.install "gogo"
        end
      end
    end
  end

  test do
    system "#{bin}/gogo", "version"
  end
end
