# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Gogo < Formula
  desc "CLI tool for generating Go projects with best practices"
  homepage "https://github.com/oculus-core/gogo"
  version "0.1.4"
  license "MIT"

  on_macos do
    on_intel do
      url "https://github.com/oculus-core/gogo/releases/download/v0.1.4/gogo_0.1.4_Darwin_x86_64.tar.gz"
      sha256 "a17a221029902f6845684b5a3cf2224740ad94440797b4433098eea2d7663f77"

      def install
        bin.install "gogo"
      end
    end
    on_arm do
      url "https://github.com/oculus-core/gogo/releases/download/v0.1.4/gogo_0.1.4_Darwin_arm64.tar.gz"
      sha256 "b8a9aa98373252b150c316057eeabbbbd2c826e0354b786765c3f71596075f75"

      def install
        bin.install "gogo"
      end
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/oculus-core/gogo/releases/download/v0.1.4/gogo_0.1.4_Linux_x86_64.tar.gz"
        sha256 "3db087080cc4cdf1840458bd94b50a29e5f2e2cdfd0e00ef1ea4869d38978dfd"

        def install
          bin.install "gogo"
        end
      end
    end
    on_arm do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/oculus-core/gogo/releases/download/v0.1.4/gogo_0.1.4_Linux_arm64.tar.gz"
        sha256 "df6e71f293cf6af78f6e3b9cac764b9c9aa95b8055d06fd468264777883f2221"

        def install
          bin.install "gogo"
        end
      end
    end
  end

  test do
    system "#{bin}/gogo", "version"
  end
end
